name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push to master (including merged PRs)
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Updating webserver.
      uses: appleboy/ssh-action@master
      with:
        host: michalkukla.xyz 
        username: svatek 
        key: ${{ secrets.svatek_ssh }}
        passphrase: ${{ secrets.svatek_ssh_pass }}
        port: ${{ secrets.svatek_port }}
        script_stop: true
        script: |
          cd repo 
          git stash
          git pull --force origin main
          sh ./restart.sh
